<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ChecklistPlantao.UI.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ChecklistPlantao.UI\ChecklistPlantao.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
  </ItemGroup>

</Project>
